---
- name: Adding nginx repo
  yum_repository:
    name: nginx
    description: nginx repo
    baseurl: "{{ nginx_baseurl }}"
    gpgcheck: true
    enabled: true

- name: Importing nginx repo GPG key
  rpm_key:
    key: http://nginx.org/keys/nginx_signing.key

- name: Installing nginx
  yum:
    name: nginx
    state: installed

- name: Updating vhost configuration
  copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
    backup: true
  notify: Restarting nginx service
