---
- name: Downloading database dump
  unarchive:
    creates: /tmp/75670316.sql
    remote_src: true
    src: "{{ deploy_db_dump }}"
    dest: /tmp

- name: Creating database
  mysql_db:
    collation: utf8_bin
    encoding: utf8
    name: abooks
    state: import
    target: /tmp/75670316.sql

- name: Creating database user
  mysql_user:
    name: abooks
    password: "{{ deploy_db_pwd}}"
    priv: 'abooks.*:all'
    state: present

- name: Cleaning up
  file:
    path: /tmp/75670316.sql
    state: absent
