---
- name: abooks frontend prerequisites installation
  hosts:
    - test
  roles:
    - base
    - percona
    - nginx
    - php

- name: abooks deployment
  hosts:
    - test
  roles:
    - deploy
