---
- name: Enabling network time synchronization
  service:
    name: ntpd
    state: reloaded
    enabled: true

- name: Updating {{ iteml }} configuration
  service:
    name: "{{ item }}"
    state: reloaded
    enabled: true

- name: Enabling bruteforce mitigation
  service:
    name: fail2ban
    state: reloaded
    enabled: true

- name: Restarting SSH service
  service:
    name: sshd
    state: reloaded
    enabled: true
