---
- name: Enabling network time synchronization
  service:
    name: ntpd
    state: reloaded
    enabled: true

- name: Updating ip6tables configuration
  service:
    name: ip6tables
    state: reloaded
    enabled: true

- name: Updating iptables configuration
  service:
    name: iptables
    state: reloaded
    enabled: true

- name: Enabling bruteforce mitigation
  service:
    name: fail2ban
    state: reloaded
    enabled: true

- name: Restarting SSH service
  service:
    name: sshd
    state: reloaded
    enabled: true
