---
- name: Setting hostname
  hostname:
    name: "{{ hostname }}"

- name: Configuring system components
  include_tasks: pkgs.yml

- name: Configuring security
  include_tasks: security.yml

- name: Waiting for...
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: ...reboot
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 42
    state: started
