---
- name: Setting hostname
  hostname:
    name: "{{ hostname }}"

- name: Configuring system components
  import_tasks: pkgs.yml

- name: Configuring security
  import_tasks: security.yml

- name: Rebooting if needed
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  when: upgraded.rc == 1 or sestatus.changed
  ignore_errors: true
  register: rebooting

- name: Waiting for host to come up
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 42
    state: started
  when: rebooting.changed
